[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Business of Artificial Intelligence: From Startups to Mega-Corporations, Companies Are Betting Big on Intelligent Technologies"
